# 这里的配置不是完整的， 完整的请看theme目录下的 config.yml 文件

menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  关于: /about/ || fa-brands fa-apple fa-bounce

nav:
  logo:
  display_title: true
  fixed: true # 固定导航栏

# Code Blocks (代碼相關)
# --------------------------------------

highlight_theme: darker #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: false # unit: px
code_word_wrap: false

# copy settings
# copyright: Add the copyright information after copied content (複製的內容後面加上版權信息)
copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50

# social settings (社交圖標設置)
# formal:
#   icon: link || the description
social:
  fab fa-github: https://github.com/Mr-wentao/blog-hexo || Github
  fa-solid fa-square-rss: /atom.xml || RSS

# Local search
local_search:
  enable: true
  preload: false
  top_n_per_article: 1
  unescape: false
  CDN:

# Image (圖片設置)
# --------------------------------------

# Favicon（網站圖標）
favicon: '/img/bog.jpg'

# Avatar (頭像)
avatar:
  img: '/img/avatar.png'
  effect: false

# Disable all banner image
disable_top_img: false

# 首页大图
index_img: '/img/top.jpeg'

# 这个是标题等距离顶部的比例
index_site_info_top: 10%
# 这里是首页大图的高度，默认是满屏幕的， 支持写法 300px/300em/300rem 
index_top_img_height: 10em
# 默认是夜间模式还是白天模式 dark/light
display_mode: light

# If the banner of page not setting, it will show the top_img
default_top_img: '/img/top.jpeg'

cover:
  # display the cover or not (是否顯示文章封面)
  index_enable: true
  aside_enable: false
  archives_enable: true
  # the position of cover in home page (封面顯示的位置)
  # left/right/both
  position: left
  # When cover is not set, the default cover is displayed (當沒有設置cover時，默認的封面顯示)
  default_cover:
    - 'https://s3.babudiu.com/iuxt//public/skeleton1.svg'

# Replace Broken Images (替換無法顯示的圖片)
error_img:
  flink: /img/friend_404.gif
  post_page: /img/404.jpg

# A simple 404 page
error_404:
  enable: true
  subtitle: 'Page Not Found 页面没有找到'
  background: https://s3.babudiu.com/iuxt//images/202210272208603.webp

post_meta:
  page: # Home Page
    date_type: created # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: false # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: date # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字


index_post_content:
  method: 3
  length: 500 # if you set method to 2 or 3, the length need to config

# toc (目錄)
toc:
  post: true
  page: false
  number: true
  expand: false
  style_simple: false
  scroll_percent: true

post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Related Articles
related_post:
  enable: true
  limit: 6 # Number of posts displayed
  date_type: created # or created or updated 文章日期顯示創建日或者更新日

# figcaption (圖片描述文字)
photofigcaption: false

# post_pagination (分頁)
# value: 1 || 2 || false
# 1: The 'next post' will link to old post
# 2: The 'next post' will link to new post
# false: disable pagination
post_pagination: 1

# Displays outdated notice for a post (文章過期提醒)
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 365 # When will it be shown
  position: top # position: top/bottom
  message_prev: 此文章距离发布已经
  message_next: 天了，内容可能已经过时，请自行判断是否可用或联系博主更新。

sharejs:
  enable: true
  sites: facebook,twitter,wechat,weibo,qq

# comments:
#   use: Giscus # Valine,Disqus
#   text: true # Display the comment name next to the button
#   lazyload: true
#   count: false # Display comment count in post's top_img
#   card_post_count: false # Display comment count in Home Page

# giscus:
#   repo: iuxt/iuxt.github.io
#   repo_id: MDEwOlJlcG9zaXRvcnkzOTAwMjMzMzQ=
#   category_id: DIC_kwDOFz9Ips4B_jcP
#   theme:
#     light: light
#     dark: dark
#   option:

# Footer Settings
# --------------------------------------
footer:
  owner:
    enable: false
    since: 2020
  custom_text: |
    <a href='https://www.upyun.com/?utm_source=lianmeng&utm_medium=referral'>
      本网站由<img src='https://s3.babudiu.com/iuxt//images/202210272253029.svg' alt='又拍云' width='70' height='28' style="vertical-align:bottom">
      提供CDN加速/云存储服务
    </a>
  copyright: false # Copyright of theme and framework

baidu_analytics: 50b516d50102c8c9ac5f80529b81ca17
google_analytics: G-YN0WWZGVYN

theme_color:
  enable: true
  main: "#5a544b"

# Beautify (美化頁面顯示)
beautify:
  enable: true
  field: post # site/post
  title-prefix-icon: '\f2db'
  title-prefix-icon-color: '#F47466'

blog_title_font:
  font_link:
  font-family:

hr_icon:
  enable: true
  icon: # the unicode value of Font Awesome icon, such as '\3423'
  icon-top:

subtitle:
  enable: true
  effect: true
  typed_option:
  source: false
  sub: 
  - 欲穷千里目，更上一层楼。
  - 学而不思则罔，思而不学则殆。

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: "阿飞的博客"
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/Mr-wentao
  card_announcement:
    enable: true
    content: |
      此博客为我记录运维工作总结所用，供网友阅读参考，如有侵权，请通知我，我会核实后进行处理。
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    orderby: random # Order of tags, random/name/length
    order: 1 # Sort of order. 1, asc for ascending; -1, desc for descending
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works

busuanzi:
  site_uv: true
  site_pv: true
  page_pv: true

darkmode:
  enable: true
  button: true
  autoChangeMode: false

fancybox: true

note:
  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0

instantpage: false

lazyload:
  enable: true
  field: site # site/post
  placeholder: https://s3.babudiu.com/iuxt//public/windmill.svg
  blur: false

Open_Graph_meta:
  enable: true
  option:

css_prefix: true

CDN:
  internal_provider: local
  third_party_provider: local
  version: false
  custom_format:
  option:

canvas_fluttering_ribbon:
  enable: true
  mobile: true

fireworks:
  enable: true
  zIndex: -1 # -1 or 9999
  mobile: false

# Add mask to header or footer (為 header 或 footer 添加黑色半透遮罩)
mask:
  header: true
  footer: false

# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    - <link rel="stylesheet" href="https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" />
    # - <link rel="stylesheet" href="https://s3.babudiu.com/iuxt//libs/lxgw-wenkai-screen-webfont/1.7.0/style.min.css" />
  bottom:
    # - <script src="xxxx"></script>

# Global font settings
# Don't modify the following settings unless you know how they work (非必要不要修改)
font:
  global-font-size:
  code-font-size:
  font-family: '"LXGW WenKai Screen", sans-serif;'
  code-font-family: